import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
       <head>
        <meta
          name="google-site-verification"
          content="7plBJ4qtylVoc-WH_xsSiqC8EUpKIQFQgjoaCVMmqhM"
        />
      </head>
      <body className="relative bg-slate-950 text-white">

  {/* Background Logo Watermark */}
  <div
    className="fixed inset-0 z-0 opacity-[0.02] bg-center bg-no-repeat bg-contain pointer-events-none"
    style={{
      backgroundImage: "url('/logo.png')",
      backgroundSize: "300px",
    }}
  />

  {/* Website Content */}
  <div className="relative z-10">
    {children}
  </div>

</body>
    </html>
  );
}
